trigger CI

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -19,7 +19,6 @@ on:
 
 # All master/tag pushes and PRs
 #
-# docker_pull
 # docker_build
 # -> kind_integration_tests
 
@@ -37,14 +36,6 @@ jobs:
   # - every PR
   #
 
-
-
-  #
-  # Docker build and kind integration tests run for:
-  # - every master push
-  # - every tag push
-  # - every PR
-  #
 
   docker_build:
     name: Docker build
@@ -192,9 +183,10 @@ jobs:
         test -f load_fail && exit 1 || true
 
         # Load proxy-init and prometheus images into KinD while it is
-        # available.
-        kind load image-archive <(DOCKER_HOST=ssh://linkerd-docker docker save $PROXY_INIT_IMAGE_NAME)
-        kind load image-archive <(DOCKER_HOST=ssh://linkerd-docker docker save $PROMETHEUS_IMAGE_NAME)
+        # available. Allow these commands to fail since they will be cached
+        # for the next run.
+        kind load image-archive <(DOCKER_HOST=ssh://linkerd-docker docker save $PROXY_INIT_IMAGE_NAME) 2>&1 || true
+        kind load image-archive <(DOCKER_HOST=ssh://linkerd-docker docker save $PROMETHEUS_IMAGE_NAME) 2>&1 || true
     - name: Load image archives into the local KinD cluster (Forked repositories)
       if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork
       run: |
@@ -215,3 +207,44 @@ jobs:
         init_test_run $HOME/.linkerd
         ${{ matrix.integration_test }}_integration_tests
 
+  #
+  # Docker push and cloud integration tests run for:
+  # - every master push
+  # - every tag push
+  #
+
+  docker_push:
+    name: Docker push
+    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
+    runs-on: ubuntu-18.04
+    needs: [go_dependencies, go_unit_tests, go_lint, js_unit_tests, kind_integration_tests]
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v2
+    - name: Set environment variables from scripts
+      run: |
+        . bin/_tag.sh
+        echo ::set-env name=TAG::$(CI_FORCE_CLEAN=1 bin/root-tag)
+    - name: Configure gcloud
+      uses: linkerd/linkerd2-action-gcloud@v1.0.0
+      with:
+        cloud_sdk_service_account_key: ${{ secrets.CLOUD_SDK_SERVICE_ACCOUNT_KEY }}
+        gcp_project: ${{ secrets.GCP_PROJECT }}
+        gcp_zone: ${{ secrets.GCP_ZONE }}
+    - name: Docker SSH setup
+      run: |
+        mkdir -p ~/.ssh/
+        touch ~/.ssh/id && chmod 600 ~/.ssh/id
+        echo "${{ secrets.DOCKER_SSH_CONFIG }}"  > ~/.ssh/config
+        echo "${{ secrets.DOCKER_PRIVATE_KEY }}" > ~/.ssh/id
+        echo "${{ secrets.DOCKER_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
+        ssh linkerd-docker docker version
+    - name: Push docker images to registry
+      env:
+        DOCKER_HOST: ssh://linkerd-docker
+      run: |
+        export PATH="`pwd`/bin:$PATH"
+        bin/docker-push-deps
+        bin/docker-push $TAG
+        #bin/docker-retag-all $TAG master
+        #bin/docker-push master
